"""autogenerated by genpy from camina3/DatosTrayectoriaRob.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class DatosTrayectoriaRob(genpy.Message):
  _md5sum = "1ac9cad93c9db8c721a8b9d4fd88e014"
  _type = "camina3/DatosTrayectoriaRob"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# datos_trayectoria.msg

float32 delta_x
float32 delta_y
float32 delta_z
float32 numeroPasos_angulo
float32 pasoAngulo
float32[] alfa


"""
  __slots__ = ['delta_x','delta_y','delta_z','numeroPasos_angulo','pasoAngulo','alfa']
  _slot_types = ['float32','float32','float32','float32','float32','float32[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       delta_x,delta_y,delta_z,numeroPasos_angulo,pasoAngulo,alfa

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DatosTrayectoriaRob, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.delta_x is None:
        self.delta_x = 0.
      if self.delta_y is None:
        self.delta_y = 0.
      if self.delta_z is None:
        self.delta_z = 0.
      if self.numeroPasos_angulo is None:
        self.numeroPasos_angulo = 0.
      if self.pasoAngulo is None:
        self.pasoAngulo = 0.
      if self.alfa is None:
        self.alfa = []
    else:
      self.delta_x = 0.
      self.delta_y = 0.
      self.delta_z = 0.
      self.numeroPasos_angulo = 0.
      self.pasoAngulo = 0.
      self.alfa = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_5f.pack(_x.delta_x, _x.delta_y, _x.delta_z, _x.numeroPasos_angulo, _x.pasoAngulo))
      length = len(self.alfa)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.alfa))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.delta_x, _x.delta_y, _x.delta_z, _x.numeroPasos_angulo, _x.pasoAngulo,) = _struct_5f.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.alfa = struct.unpack(pattern, str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_5f.pack(_x.delta_x, _x.delta_y, _x.delta_z, _x.numeroPasos_angulo, _x.pasoAngulo))
      length = len(self.alfa)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.alfa.tostring())
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.delta_x, _x.delta_y, _x.delta_z, _x.numeroPasos_angulo, _x.pasoAngulo,) = _struct_5f.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.alfa = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_5f = struct.Struct("<5f")
