#Trayectorias en mundo

float32   x_UbicacionRob
float32   y_UbicacionRob
float32   theta_Rob

#Pata1
float32[] trayectoriaPata1_x
float32[] trayectoriaPata1_y
float32[] trayectoriaPata1_z
#Pata2
float32[] trayectoriaPata2_x
float32[] trayectoriaPata2_y
float32[] trayectoriaPata2_z
#Pata3
float32[] trayectoriaPata3_x
float32[] trayectoriaPata3_y
float32[] trayectoriaPata3_z
#Pata4
float32[] trayectoriaPata4_x
float32[] trayectoriaPata4_y
float32[] trayectoriaPata4_z
#Pata5
float32[] trayectoriaPata5_x
float32[] trayectoriaPata5_y
float32[] trayectoriaPata5_z
#Pata6
float32[] trayectoriaPata6_x
float32[] trayectoriaPata6_y
float32[] trayectoriaPata6_z
