"""autogenerated by genpy from camina3/AngulosMotor.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class AngulosMotor(genpy.Message):
  _md5sum = "3caf673a31c15eb131585a12307d71e2"
  _type = "camina3/AngulosMotor"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# motor.msgAngulos
# Angulos de motores calculados por cinematica inversa para la pata "Npata"
# contador de iteracion

uint8 iteracion
uint8 Npata
float32 q1
float32 q2
float32 q3



"""
  __slots__ = ['iteracion','Npata','q1','q2','q3']
  _slot_types = ['uint8','uint8','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       iteracion,Npata,q1,q2,q3

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AngulosMotor, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.iteracion is None:
        self.iteracion = 0
      if self.Npata is None:
        self.Npata = 0
      if self.q1 is None:
        self.q1 = 0.
      if self.q2 is None:
        self.q2 = 0.
      if self.q3 is None:
        self.q3 = 0.
    else:
      self.iteracion = 0
      self.Npata = 0
      self.q1 = 0.
      self.q2 = 0.
      self.q3 = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2B3f.pack(_x.iteracion, _x.Npata, _x.q1, _x.q2, _x.q3))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 14
      (_x.iteracion, _x.Npata, _x.q1, _x.q2, _x.q3,) = _struct_2B3f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2B3f.pack(_x.iteracion, _x.Npata, _x.q1, _x.q2, _x.q3))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 14
      (_x.iteracion, _x.Npata, _x.q1, _x.q2, _x.q3,) = _struct_2B3f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2B3f = struct.Struct("<2B3f")
