from ._commData import *
from ._CoordenadasPatas import *
from ._SenalesCambios import *
from ._InfoMapa import *
from ._DatosTrayectorias import *
from ._AnguloParaVrep import *
from ._UbicacionRobot import *
from ._DatosTrayectoriaRob import *
from ._AngulosMotor import *
from ._DatosTrayectorias2 import *
from ._DatosTrayectoriaPata import *
from ._Punto import *
from ._Pisada import *
